; cnc-ddraw configuration for Dune 2000 on Snapdragon 870 / Termux-X11
[ddraw]
renderer = opengl
fullscreen = true
windowed = false
borderless = true
maintas = true
boxing = false
maxfps = 60
minfps = -1
vsync = false
filter = linear
clipcursor = true
handlemouse = true
adjmouse = true
mousehook = 2
vhack = false
singlecpu = false
noactivateapp = true
nonexclusive = true
hookallerrors = false
devmode = false
accuratetimers = true

[dune2000]
renderer = opengl
fullscreen = true
windowed = false
borderless = true
maintas = true
boxing = false
maxfps = 60
minfps = -1
vsync = false
filter = linear
clipcursor = true
handlemouse = true
adjmouse = true
mousehook = 2
singlecpu = false
nonexclusive = true
vhack = false
accuratetimers = true
